### ISSUE TITLE
Issue with the start.sh script

### ISSUE THREAD

**Issue by balteo** [SourceLabOrg/kafka-webview#100]
Hello,

When one uses the start.sh script, `java jar` tries to start the following jar: `kafka-webview-ui-2.0.0-javadoc.jar` instead of this one: `kafka-webview-ui-2.0.0.jar`.

See this line: https://github.com/SourceLabOrg/kafka-webview/blob/master/kafka-webview-ui/src/assembly/distribution/start.sh#L20

```
## launch webapp
java -jar kafka-webview-ui-*.jar $HEAP_OPTS $LOG_OPTS

```
I had to modify the script as follows:

```
## launch webapp
java -jar kafka-webview-ui-2.0.0.jar $HEAP_OPTS $LOG_OPTS
```
In order for the spring boot app to start.

**Comment by Crim** [comment]
@balteo How did you build your docker image?  If you have the code checked out locally and ran:
```bash
docker build -t kafka-webview .
```

Inside the image the filesystem should look like below.  Part of the Docker file removes the unnecessary JAR files from the release package.

```bash
spowis-ltm2:kafka-webview spowis$ docker run -it --entrypoint /bin/bash kafka-webview
bash-4.4# ls
config.yml                  kafka-webview-ui-2.0.0.jar  logs                        start.sh
data                        lib                         start.bat
bash-4.4# ls -l
total 46624
-rw-r--r--    1 root     root           696 Oct  1 07:41 config.yml
drwxr-xr-x    2 root     root          4096 Oct  1 07:29 data
-rw-r--r--    1 root     root      47718142 Oct  1 07:41 kafka-webview-ui-2.0.0.jar
drwxr-xr-x    2 root     root          4096 Oct  1 07:41 lib
drwxr-xr-x    2 root     root          4096 Oct  1 07:29 logs
-rw-r--r--    1 root     root           145 Oct  1 07:41 start.bat
-rwxr-xr-x    1 root     root           436 Oct  1 07:41 start.sh
```

What does your image look like?

**Comment by balteo** [comment]
@Crim This issue is about the zip version.

**Comment by Crim** [comment]
Ah you're definitely correct.

**Comment by Crim** [comment]
Put together the above PR.  Still not the most ideal solution as I'm still using a wildcard.  I'm trying to avoid having to remember to update the start.bat/start.sh scripts for every release.  Perhaps there's a better approach?

**Comment by Crim** [comment]
released 2.0.1, should resolve this issue going forward.

**Comment by Crim** [comment]
Thanks for reporting the issue! ❤️

**Comment by balteo** [comment]
You're welcome !
