### ISSUE TITLE
SASL Authentication

### ISSUE THREAD

**Issue by nadeevkm** [SourceLabOrg/kafka-webview#105]
Greeting! Is it possible to use kafka-webview with a cluster with a SASL authenticaton? In simple console consumer I can do this by just passing jaas conf(with login/password) file as JVM argument like 

export KAFKA_OPTS="-Djava.security.auth.login.config=/home/nkm/Apps/kafka_2.11-2.0.0/config/jaas_client.conf"

and consumer.property file with lines

security.protocol=SASL_PLAINTEXT
sasl.mechanism=PLAIN 

as cmd arguments, like.. 

bin/kafka-console-consumer.sh --bootstrap-server localhost:9029092 --topic test_topic --from-beginning --consumer.config config/consumer.properties

**Comment by thammuio** [comment]
@Crim - I can help with this. What distro of Kafka you need? (Apache/Horotonworks/Cloudera/Confluent)...

This is a good doc which covers all vendor distros... Probably you need to setup a KDC, if you don't have one already.

**Comment by Crim** [comment]
just standard Apache's Kafka, or whatever is easiest to get up and going really.

Thanks!

**Comment by nadeevkm** [comment]
Glad to hear, it would be great!

As far as SASL is concerned - it's quite a simple thing when you get it, so I can describe it here.

To setup SASL authentification in a kafka cluster you shoul fulfill several steps:

1. Add relevant properties in properies files
2. Make jaas-file with authentication information
3. Pass JVM a special environment parametr
4. Run zookeeper/kafka/producers/consumers explicitly passing modifyed config files

Now in details:

1) Zookeper

add this at config/zookeeper.properies

	authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
	requireClientAuthScheme=sasl
	jaasLoginRenew=3600000

make jaas file, for example  config/jaas_zookeeper.conf with lines

	Server {
	   org.apache.kafka.common.security.plain.PlainLoginModule required
	   username="admin"
	   password="admin-secret"
	   user_zooclient="client-secret";
	};

pass JVM a special param, in linux you can do it this way:

	export KAFKA_OPTS="-Djava.security.auth.login.config=/home/nkm/apps/kafka_2.11-2.0.0/config/jaas_zookeeper.conf"

and run zookeeper

	bin/zookeeper-server-start.sh config/zookeeper.properties

2) Kafka broker

modify or add this properies at config/server.properies

	advertised.host.name=localhost
	advertised.listeners=SASL_PLAINTEXT://localhost:9092

	allow.everyone.if.no.acl.found=true
	authorizer.class.name=kafka.security.auth.SimpleAclAuthorizer

	listeners=SASL_PLAINTEXT://localhost:9092
	sasl.enabled.mechanisms=PLAIN
	sasl.mechanism.inter.broker.protocol=PLAIN
	security.inter.broker.protocol=SASL_PLAINTEXT
	super.users=User:admin

make jaas file, for example  config/jaas_kafka_server.conf with lines

	KafkaServer {
	   org.apache.kafka.common.security.plain.PlainLoginModule required
	   username="admin"
	   password="admin-secret"
	   user_admin="admin-secret"
	   user_kafkaclient="client-secret";
	};

	Client {
	       org.apache.zookeeper.server.auth.DigestLoginModule required
	       username="zooclient"
	       password="client-secret";
	};

pass JVM a special param, in linux you can do it this way:

	export KAFKA_OPTS="-Djava.security.auth.login.config=/home/nkm/apps/kafka_2.11-2.0.0/config/jaas_kafka_server.conf"

and run kafka broker

	bin/kafka-server-start.sh config/server.properties


3) Kafka producer/consumer

make config/client.properties and add this

	security.protocol=SASL_PLAINTEXT
	sasl.mechanism=PLAIN

make jaas file, for example  config/jaas_kafka_client.conf with lines

	KafkaClient {
	  org.apache.kafka.common.security.plain.PlainLoginModule required
	  username="kafkaclient"
	  password="client-secret";
	};

pass JVM a special param, in linux you can do it this way:

	export KAFKA_OPTS="-Djava.security.auth.login.config=/home/nkm/apps/kafka_2.11-2.0.0/config/jaas_kafka_client.conf"

and run producer

	bin/kafka-console-producer.sh --broker-list localhost:9092 --topic test_topic --producer.config config/client.properties

run consumer

	bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic test_topic --from-beginning --consumer.config config/client.properties 


So after all kafka broker connects to Zookeper using Client data in jaas file (it must correspond to zookeeper Server jaas data) and consumers and producers connect to broker using KafkaClient jaas data (it must correspond to KafkaServer authentication data)

And don't forget to replace "/home/nkm/apps/kafka_2.11-2.0.0" with your own kafka directory)

**Comment by Crim** [comment]
How does this UI look for setting up a cluster using SASL?  Any suggestions or improvements?

### Plain SASL authentication
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/571653/49692197-00186680-fb98-11e8-80b2-7fb10a035191.png">

### GSSAPI / Custom Mechanism
Selecting GSSAPI or a Custom mechanism would basically just prompt you to enter your own JAAS configuration manually.
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/571653/49692199-2807ca00-fb98-11e8-9def-5cce2e3da9b9.png">

**Comment by Crim** [comment]
Just to make sure I'm understanding correctly....since the app already supports PLAINTEXT and SSL, when I add SASL support, 

- PLAIN when you don't have SSL or SASL options enabled
- SSL when you have just the currently supported SSL options enabled.
- SASL_PLAIN when you do NOT have the currently supported SSL settings enabled, and have the new SASL settings enabled.
- SASL_SSL a combination of the existing SSL settings enabled, as well as the new SASL settings

This sounds correct?

**Comment by thammuio** [comment]
@Crim  yes you are right. 


One thing to point out is when we have SASL_SSL; we just use truststore(no ssl Auth - so keystore is not needed).

**Comment by Crim** [comment]
Good to know!

**Comment by Crim** [comment]
I've published a new release that should support this.  Thanks!

**Comment by nadeevkm** [comment]
Thank you very much for your work! I'll check It in a few days!

**Comment by thammuio** [comment]
Thanks @Crim. when we have SASL auth, we dont need SSL auth; can you check on this; for SASL_SSL we just need SASL conf and SSL truststore.

![image](https://user-images.githubusercontent.com/6325610/50290022-0af0b800-0430-11e9-943c-d06b47e3999f.png)

**Comment by thammuio** [comment]
I am able to setup with SASL. I can use it. But, i am getting below error in Cluster Broker View:

Error: org.apache.kafka.common.errors.UnsupportedVersionException: The broker does not support DESCRIBE_CONFIGS

**Comment by thammuio** [comment]
Thanks @Crim . Yes, when SASL is enabled no need of keystore details.

**Comment by Crim** [comment]
created issue #116 to deal with no longer requiring a KEYSTORE in this scenario and closing out this ticket.

Thanks!
