### ISSUE TITLE
The broker does not support DESCRIBE_CONFIGS

### ISSUE THREAD

**Issue by Crim** [SourceLabOrg/kafka-webview#115]
i am getting below error in Cluster Broker View:

Error: org.apache.kafka.common.errors.UnsupportedVersionException: The broker does not support DESCRIBE_CONFIGS

**Comment by Crim** [comment]
Looks like this happens on version 0.10.2.x ?

Apparently the app isn't compatible with any version prior to that at all.  Let me see if I can handle this more gracefully in the app.

**Comment by thammuio** [comment]
Yes.. i am on Kafka 0.10.2.x..

**Comment by Crim** [comment]
So it looks like that operation is just not supported against 0.10.x version clusters.  As far as I can tell the app handles the error in a fairly graceful way (doesn't server 500, presents a relevant error message to the user) and doesn't prevent the user from accessing other available operations.

Feel free to reopen the issue if you disagree with my assessment or if you think there's a better way to handle this situation :)
