### ISSUE TITLE
Unable to view consumer group

### ISSUE THREAD

**Issue by sujittripathy** [SourceLabOrg/kafka-webview#122]
Hi,
I have configured kafka-webview to connect my Kafka cluster. I am seeing an issue is that the consumer groups pertaining to the topic is being viewed in ```Cluster DEV Consumer Groups``` section on my Cluster Explorer page. However, I have configured ```Kafka Tool``` desktop UI in my local which is showing all the consumer groups and messages nicely. Is there anything I am missing or need to be configured in the configuration yaml files?

Thanks
Sujit

**Comment by Crim** [comment]
Hi @sujittripathy 

What version is your kafka cluster and what version consumers are you using?  Do you know if your consumer group offsets are stored within Kafka, or within a zookeeper instance?

KafkaWebView currently only supports viewing consumer groups which store their state within Kafka.  My guess is your consumers are storing their state in Zookeeper instead, are you able to confirm this?

If not, it's possible something else is going on.

Thanks
Stephen

**Comment by sujittripathy** [comment]
Hi @Crim 
I am using Kafka cluster version 0.10.0.1 and I am using spring-kafka integration v1.2.1 which has the same version on the consumer. I believe now I am seeing the consumer group (CG.PMTS.CARD.EVENTS) in the list on the view page, however upon clicking on the link I am seeing the below error and the section ```Consumer CG.PMTS.CARD.EVENTS Positions``` is not loading. I am seeing a topic exists named as ```__consumer_offsets``` which stores the offsets in Kafka seems. Is the below error related to any versioning issue on the KafkaWebView and the connecting Kafka cluster?

```

Error org.apache.kafka.common.errors.UnsupportedVersionException: The broker only supports OffsetFetchRequest v1, but we need v2 or newer to request all topic partitions. (show more)
java.lang.RuntimeException thrown at org.sourcelab.kafka.webview.ui.manager.kafka.KafkaOperations::getConsumerGroupOffsets -> org.apache.kafka.common.errors.UnsupportedVersionException: The broker only supports OffsetFetchRequest v1, but we need v2 or newer to request all topic partitions.
java.util.concurrent.ExecutionException thrown at org.apache.kafka.common.internals.KafkaFutureImpl::wrapAndThrow -> org.apache.kafka.common.errors.UnsupportedVersionException: The broker only supports OffsetFetchRequest v1, but we need v2 or newer to request all topic partitions.
org.apache.kafka.common.errors.UnsupportedVersionException thrown at -> The broker only supports OffsetFetchRequest v1, but we need v2 or newer to request all topic partitions.
```

**Comment by Crim** [comment]
Sorry for the super delayed response.  I believe that feature is not supported on brokers older than 0.11.0.x
