### ISSUE TITLE
Running Kafka Webview behind AWS ALB

### ISSUE THREAD

**Issue by sarunask** [SourceLabOrg/kafka-webview#133]
We are running Kafka Webview behind AWS ALB.
Network setup looks like this:
HTTPS -> AWS ALB -> HTTP -> Kafka-Webview

Issue is that we get after login such URL's, which are incorrect ones:
http://kafka-webviews.domain.com:443/view?UserId=2&MenuShowUserConfig=true

It should be using HTTPS instead of HTTP. How to force Kafka-Webview to run correctly in such setup?

**Comment by Crim** [comment]
I believe you can configure the `requireSsl` field to `true` in your configuration file.

[Basically this line](https://github.com/SourceLabOrg/kafka-webview/blob/master/kafka-webview-ui/src/assembly/distribution/config.yml#L22-L23).

Let me know if that solves it for you!

**Comment by Crim** [comment]
Sorry for the super delayed response.

So using [this as a reference](https://stackoverflow.com/questions/48197756/aws-elb-https-to-http-using-spring-boot-mvc-login-not-working) is it possible to add the following option to your configuration yaml:

```yaml
```

**Comment by sarunask** [comment]
Yes this one helped - thank you :)
