### ISSUE TITLE
Support running Kafka Webview behind reverse proxy

### ISSUE THREAD

**Issue by wkerckho** [SourceLabOrg/kafka-webview#136]
I am running Kafka Webview in a Kubernetes cluster and I'm trying to expose it publicly using Kubernetes Ingress (reverse proxy mechanism, backed by traefik).

I want to setup a reverse proxy rewrite rule that translates all external requests that matche the path prefix `/dashboards/kafka` to `/` on the service that is running Kafka Webview. This works for accessing the index page or the static resources, but the page links are incorrent and redirects fail, because your are using absolute paths in the JSP templates (e.g. the authentication procedure  automatically redirects to `/login`, but should be `login` so it is externally reachable from `/dashboards/kafka/login` through the reverse proxy).

Another solution could be to use the Spring Boot `server.servlet.configPath` configuration property. Using this property I could set a prefix path for the Kafka Webview (`dashboards/kafka`) and let the reverse proxy redirect the paths as-is. For this to work, I guess you should add the variable `${pageContext.request.contextPath}` before all href paths?

Or is there another easy workaround?

**Comment by Crim** [comment]
So I've made a first pass in the above PR to properly prefix the URLs in the templates making use of the `server.servlet.context-path` configuration property which can be defined in the application.yml file distributed with each release.

Unfortunately the above PR doesn't handle ALL of the URLs, most notably any generated from within javascript, or some links defined in CSS files (like font-awesome).  I'll have to do some tinkering around to figure out how to sort those out.

**Comment by Crim** [comment]
OK, I believe master now contains the required fixes to make this work.  Are you able to validate from master? 

You'll need to edit your config.yml file and add the following:

```yml
server:
  servlet:
    context-path: /prefix/here
```

**Comment by wkerckho** [comment]
I checked the master and I was able to successfully set a context-path. Routing through the reverse proxy is now possible! Thank you very much!

Any idea on when this version might be available as a Docker image?

**Comment by Crim** [comment]
I'll cut a release tomorrow for you, let me know if you run into any issues before that.

Thanks for reporting the issue!

**Comment by Crim** [comment]
Docker images should be updated.

**Comment by wkerckho** [comment]
Super! I've got the Kafka Webview up and running in our Kubernetes cluster now!

**Comment by Crim** [comment]
Great, going to close out this issue.  Will post up a proper release here on github shortly.

**Comment by wkerckho** [comment]
Could it be that the websocket endpoint for the streaming view still needs to be prefixed?

When I click the connect button, it tries a `GET https://myhost/websocket/info?t=1550846293947`, but this should also be `GET https://myhost/{configured pathPrefix}/websocket/info?t=1550846293947`.
