### ISSUE TITLE
search for topic

### ISSUE THREAD

**Issue by tomas12** [SourceLabOrg/kafka-webview#142]
Hi, your app is really cool. What I miss is a possibility to search and remove topics. When testing we are dealing with many topics and this would make life more easier. Thanks!

**Comment by Crim** [comment]
So you'd like a search option added here to quickly locate topics?  And then the possibility to remove topics?

<img width="958" alt="image" src="https://user-images.githubusercontent.com/571653/53675437-c5baf300-3cc8-11e9-9d44-baaf9d61477e.png">

**Comment by tomas12** [comment]
Yes that would be great. Deletion could work like the one at the Consumer Group (on the right side). And especially when dealing with many topics a search would be also very helpful

**Comment by midN** [comment]
If you ever go implementing the delete/management features, can we get roles in place please @Crim ?
Would be lovely to have a read-only role

**Comment by Crim** [comment]
Yea that's definitely a concern.  I've been trying to keep all of the features so far non-destructive.  

I've got an initial implementation for this in PR #150  where deleting a topic requires the Administrator credential.  Unsure if I should hold back the removing functionality until we have more fine grained control over roles/abilities.

**Comment by midN** [comment]
@Crim Thanks for working on this 👍 I'd vote that roles is a must for any future destructive changes as there is kafka-manager from yahoo for destructive-only action and this is basically the only app on market that allows to give easy read-only access for teams to view data without killing the kafka

**Comment by tomas12** [comment]
Thank you too for working on this!

**Comment by Crim** [comment]
I've added searching to a few spots under the 'Cluster Explorer' section of the application.  

While its now implemented, I think I'm going to hold back the removal of topics until custom user roles is released.  I've got that started in a separate ticket, but not entirely sure how long before that work will be complete.

**Comment by Crim** [comment]
I've created #157 to track deletion of topics.

**Comment by Crim** [comment]
Released in [2.2.0](https://github.com/SourceLabOrg/kafka-webview/releases/tag/v2.2.0)
