### ISSUE TITLE
SSL without truststore and truststore password

### ISSUE THREAD

**Issue by Vladutu** [SourceLabOrg/kafka-webview#144]
I would want to connect to kafka cluster with SSL_SASL enabled but without providing any truststore/keystore. Can you update to have the truststore optional?

**Comment by daaaaa** [comment]
I have the same issue.
Is there any additional information I can provide?

**Comment by Crim** [comment]
> I have the same issue.
> Is there any additional information I can provide?

Hi!  
If possible an example configuration for a Kafka broker with the setup so I can replicate and test it locally would be super helpful.  

Thanks!

**Comment by daaaaa** [comment]
Unfortuntaley I have no access to the Kafka Broker Configuration.
I am currently using Confluent Cloud that offers a Kafka SaaS.

This is a command that I usually use to contact kafka:
`./bin/kafka-topics.sh --command-config properties.txt --bootstrap-server hostname:port`

And this is the content of the `properties.txt` file:
`
ssl.endpoint.identification.algorithm=HTTPS
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="MY-USERNAME" password="MY-PASSWORD";
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
request.timeout.ms=20000
`

If you want and you can provide a Docker image I can test, I can try to test if the fix works.

I am also open to other solutions, if you have other ideas.

Thanks for the quick reply!

**Comment by Vladutu** [comment]
When i first posted this question I also got the code to see if I can do something to make it work and I managed to do it, but being more than 1 year ago i don't remember exactly. I know that i disabled the check for truststore in the UI and in the backend I set the filename to null. This is how the config looks in the UI:
<img width="1116" alt="Screenshot 2020-06-05 at 12 05 23" src="https://user-images.githubusercontent.com/9379045/83858390-166b9800-a725-11ea-93e0-2ba0f9657d28.png">

Here are the config elements used in my application that read/writes from kafka. They are for spring but I think they are 1-to-1 to the actual kafka properties
```
SPRING_KAFKA_BOOTSTRAPSERVERS: "server:9092"
SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
SPRING_KAFKA_PROPERTIES_SASL_MECHANISM: PLAIN
SPRING_KAFKA_JAAS_ENABLED: "true"
SPRING_KAFKA_JAAS_CONTROL: required
SPRING_KAFKA_JAAS_LOGIN_MODULE: "org.apache.kafka.common.security.plain.PlainLoginModule"
SPRING_KAFKA_JAAS_OPTIONS_USERNAME: user
SPRING_KAFKA_JAAS_OPTIONS_PASSWORD: password
SPRING_KAFKA_PRODUCER_COMPRESSIONTYPE: lz4
```

**Comment by Crim** [comment]
Off on vacation for the weekend, but I'll try to take a look in the next week.  

Thanks!

**Comment by daaaaa** [comment]
I have played a little with the code and to make it work it was enough to comment out the four last line of codes in here:

https://github.com/SourceLabOrg/kafka-webview/blob/fb860ca2839c39010252711077db152c06167b8b/kafka-webview-ui/src/main/java/org/sourcelab/kafka/webview/ui/manager/kafka/config/ClusterConfig.java#L173-L179

Unfortunately, I can work on it during weekend only and I have all the month weekends busy.
If i find the time and you have not done it yet, I will be more than happy to submit a PR.

**Comment by Crim** [comment]
Reviewing this now that I'm back at home.  To make sure I understand correctly, in this scenario the JVM running kafka-webview is already configured to trust the certificate being served by your kafka cluster correct?  And therefore there is no reason to upload a truststore?

I should be able to mock up this locally without much effort.  How would you expect the UI to be presented?  Something along the lines of:

- Use SSL Authentication? [ Checkbox ]
  -  If Checked then show: Do you need to supply a truststore for this server? [ Checkbox ]
     - If Checked then show the TrustStore upload UI as it exists.
     - If NOT checked, no need to display the truststore upload UI.  No truststore file will be passed to the underlying kafka client connection.

Does that sound about right?

**Comment by daaaaa** [comment]
> To make sure I understand correctly, in this scenario the JVM running kafka-webview is already configured to trust the certificate being served by your kafka cluster correct? And therefore there is no reason to upload a truststore?

Exactly. In my scenario internet is reachable and the certificate can be verified using the public certificate of the CA.

> I should be able to mock up this locally without much effort. How would you expect the UI to be presented? Something along the lines of:

Use SSL Authentication? [ Checkbox ]
If Checked then show: Do you need to supply a truststore for this server? [ Checkbox ]
If Checked then show the TrustStore upload UI as it exists.
If NOT checked, no need to display the truststore upload UI. No truststore file will be passed to the underlying kafka client connection

I expect exactly this behavior :)

**Comment by Crim** [comment]
Great, thanks for the confirmation.  I started poking around at this a bit today.

**Comment by Crim** [comment]
I've got this mocked up locally, will push a pull request shortly.

**with uploading a truststore** (previous behavior)
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/571653/84122393-56a77f00-aa73-11ea-8831-8b042accdf5c.png">

**without requiring a truststore** (new behavior)
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/571653/84122432-62934100-aa73-11ea-8919-b3f480304e83.png">

**Comment by Crim** [comment]
I'll try to cut a release soon with this change.  There are a couple other minor updates I'd like to sneak into the same release if possible.

**Comment by Crim** [comment]
release 2.6.0 with this included.
