### ISSUE TITLE
Ability to disable Server host name verification

### ISSUE THREAD

**Issue by Richard-Mathie** [SourceLabOrg/kafka-webview#145]
As par: https://kafka.apache.org/documentation.html#security_confighostname
its sometimes necessary to disable https hostname verification to connect to a cluster.

> `ssl.endpoint.identification.algorithm=`

Is it possible to add this option in the cluster configuration?

in fact it would be great if we could just put the contents of the `connection.properties` file in there

**Comment by Crim** [comment]
Hey @Richard-Mathie this makes a lot of sense!  I've created an issue to track this.  

Thanks!

**Comment by ebcFlagman** [comment]
I would also have this feature soon. Have you any plans when to implement?

**Comment by Crim** [comment]
Hi!

The current unreleased version (2.7.0) checked into master can handle this situation by way of setting a custom client property when setting up the cluster.  See the attached screen shot below.

I'll work on releasing version 2.7.0 today

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/571653/94320935-34f1e980-ffc9-11ea-8431-5d830999319b.png">

**Comment by Crim** [comment]
I've released version 2.7.0.

Please re-open this issue if you are unable to solve this problem using this new feature in the 2.7.0 release.

Thanks!
