### ISSUE TITLE
Websockets behind proxy don't work

### ISSUE THREAD

**Issue by midN** [SourceLabOrg/kafka-webview#158]
Hey there,

Looks like Websockets aka Streaming behind proxy doesn't seem to work :(
I have Webview running in Kube, SSL termination happens on LB side, website is accessed over HTTPS.

Once we try to establish websocket connection, the backend responds with 403 and errors with following:
```
WARN 8 --- [nio-8080-exec-7] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved exception caused by handler execution: org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation
```

Is there an easy way to enable Debug log through ENV variable or something similar to get more info on the error?

cc @Crim

**Comment by Crim** [comment]
Hey!

I'm guessing you're using the latest release 2.2.0?  Are you able to send over a HAR file from your browser requests and the responses from the server?

A bit of googling seems to indicate that's error is typical of trying to JSON encode (and failing) an object and send it over the wire to the browser, so that is driving my following questions here, but I could be wrong --  Are you using a custom deserializer for the data in your kafka topic?  If so, does switching to say just the String deserializer work?  And are you able to browse through the topic without issue using the standard non-websocket view?

**Comment by mvdstam** [comment]
Hi @Crim, @midN,

Just wanted to chime in -- we're getting the same issues here. Our `kafka-webview` instance runs behind a `haproxy` instance which terminates SSL. So fundamentally probably identical to the setup of @midN.

To answer your questions in full:

> Are you using a custom deserializer for the data in your kafka topic? If so, does switching to say just the String deserializer work?

No, both the default deserializers and custom deserializers don't work with streams

> And are you able to browse through the topic without issue using the standard non-websocket view?

Yes, the non-stream view works fine.

From what I can tell from inspecting the network requests in Chrome, the problem doesn't seem specific to the `wss` protocol. As a matter in fact, the `http POST` call as illustrated below fails with a `HTTP-403` as well:

```sh
curl 'https://kafka-webview.[redacted]/websocket/493/zux2u4mr/xhr_streaming?t=1559053940691' -X POST -H 'origin: https://kafka-webview.[redacted]' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-GB,en;q=0.9,en-US;q=0.8,nl;q=0.7' -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36' -H 'accept: */*' -H 'referer: https://kafka-webview.[redacted]/stream/1' -H 'authority: kafka-webview.[redacted]' -H 'cookie: JSESSIONID=[redacted]' -H 'content-length: 0' --compressed
```

We're using `kafka-webview:2.2.0` as a docker image. Hope this helps you to find the cause of the problem. Please let me know if I can do anything to clarify anything else.

**Comment by VTommyV** [comment]
Did anyone make progress on getting this working? I'm currently also getting the 403 trying to use websockets behind a reverse proxy. I get the same issue with Apache and HAProxy.

**Comment by Crim** [comment]
Hi @VTommyV Have you tried the [steps outlined here](https://github.com/SourceLabOrg/kafka-webview#reverse-proxy-setup)?  Do you have the websocket reverse proxy module loaded in your configuration?

**Comment by VTommyV** [comment]
Hi @Crim , Yes using that exact config from the readme. I have the requested modules loaded:
proxy,proxy_http,proxy_balancer,lbmethod_byrequests,proxy_wstunnel. The streaming works fine when running directly but breaks as soon as its behind the reverse proxy. I've tried this with Apache and HAProxy with no luck.

**Comment by Crim** [comment]
Unfortunately this seems more like a configuration issue with haproxy/apache/etc.. over a software issue with kafka-webview, so it's difficult for me to help/diagnose.

If you're able to post more details about your setup (Software involved, versions, configuration files, etc..) I can do my best to help you get to the bottom of it.

**Comment by Crim** [comment]
I went thru and set this up locally.....I'll be updating the README with more detailed documentation on this.  But until that's up, please follow these directions:

## Setting up Kafka-WebView behind httpd (apache) reverse proxy.

The following steps have been verified against Apache Httpd version **2.4.5** and higher.

This guide assumes you've already successfully installed apache httpd.  If not, we recommend you review [Compiling and Installing](http://httpd.apache.org/docs/2.4/install.html) documentation.

### Loading Modules

You must configure HTTPD to load the following modules:
- proxy_module
- proxy_http_module
- proxy_wstunnel_module
- rewrite_module

Typically in your `httpd.conf` file you ensure the following lines exist:

```
LoadModule proxy_module libexec/apache2/mod_proxy.so
LoadModule proxy_http_module libexec/apache2/mod_proxy_http.so
LoadModule proxy_wstunnel_module libexec/apache2/mod_proxy_wstunnel.so
LoadModule rewrite_module libexec/apache2/mod_rewrite.so
```

### Standard Reverse Proxy

Follow these steps if you want to configure a reverse proxy with **no URL prefix**.

In the following example lets assume:
- **kafka-webview.example.com** is the hostname your reverse proxy is serving requests on.
- **internal-hostname:8080** is the hostname Kafka-WebView is listening for requests on.  

Add a new VirtualHost entry to HTTPD. It should be configured to look like: 

```
<VirtualHost *:80>
    ServerName kafka-webview.example.com
    
    RewriteEngine on
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule .* "ws://internal-hostname:8080%{REQUEST_URI}" [P]
    
    ProxyPass / http://internal-hostname:8080/
    ProxyPassReverse / http://internal-hostname:8080/
    ProxyRequests off
</VirtualHost>
```

Alternatively, if you'd like to **avoid using MOD_REWRITE** you can use the following example:

```
<VirtualHost *:80>
    ServerName kafka-webview.example.com
    
    ProxyPass         /websocket/info http://internal-hostname:8080/websocket/info
    ProxyPassReverse  /websocket/info http://internal-hostname:8080/websocket/info
    ProxyPass         /websocket/ ws://internal-hostname:8080/websocket/
    ProxyPassReverse  /websocket/ ws://internal-hostname:8080/websocket/
    ProxyPass         / http://internal-hostname:8080/ nocanon
    ProxyPassReverse  / http://internal-hostname:8080/
    ProxyRequests off
</VirtualHost>
```

**Comment by Crim** [comment]
[Posted Documentation here](https://github.com/SourceLabOrg/kafka-webview/blob/master/docs/httpdReverseProxySetup.md).  Let me know if this helps?

**Comment by VTommyV** [comment]
Hi @Crim you were right I think this was more of a proxy configuration issue than anything with kafka-webview. I was getting some odd results previously which was possibly down to browser behavior, but with your help I now have it working with HAProxy and Apache2. For reference this is my working config for a secure frontend and backend (Kafka-webview and proxy both running on HTTPS) :
Apache:
```
<IfModule mod_ssl.c>
<VirtualHost *:443>

    ServerName mysite.com

    SSLEngine on
    SSLCertificateFile      /etc/ssl/private/mycert.crt
    SSLCertificateKeyFile       /etc/ssl/private/mycert.key

    SSLProxyEngine on
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerExpire off

    RewriteEngine on
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule .* "wss://myserverip:8443%{REQUEST_URI}" [P]

    ProxyPass / https://myserverip:8443/
    ProxyPassReverse / https://myserverip:8443/
    ProxyRequests off

</VirtualHost>
</IfModule>
```

 HAProxy:

```
frontend web
        bind :::443 ssl crt /etc/ssl/private/mycert.pem
        mode http
        option httplog
        redirect scheme https code 301 if !{ ssl_fc }

        acl acl_kafka-webview path_beg /
        use_backend kafka-webview if acl_kafka-webview

        maxconn 1000

backend kafka-webview
        http-request set-header X-Forwarded-Port %[dst_port]
        http-request add-header X-Forwarded-Proto https if { ssl_fc }

        option forwardfor # This sets X-Forwarded-For

        server myserver myserverip:8443 ssl verify none check
```


Thanks again for pointing me in the right direction @Crim

**Comment by Crim** [comment]
Awesome!  Glad we could sort it out! :)
