### ISSUE TITLE
Unable to add custom formats on windows

### ISSUE THREAD

**Issue by BDeus** [SourceLabOrg/kafka-webview#159]
Hi,
i had several issues to add a custom format in a windows environment.
However i sucessfully add it on docker env.
I think the issue is cause by "file://" in the java library loader url.
It could be nice to fix it or at least note that it this feature doesn't work on windows.

**Comment by Crim** [comment]
Unfortunately at the moment I don't have a Windows environment in which I can validate changes against.  Is this something you might be able to help commit a fix for?

Thanks!
Stephen

**Comment by Crim** [comment]
Scheduling the fix for this to be in the 2.3.0 release.
