### ISSUE TITLE
Search and Filtering interface is confusing and inconsistent

### ISSUE THREAD

**Issue by cryptk** [SourceLabOrg/kafka-webview#161]
I have just added the StringSearchFilter from the examples repository, and trying to figure out how to get the configured search and filters to actually apply was quite difficult.  It turns out that I need to put in the string I want to search for... and then click one of the page/seek buttons on the browse list...

Would it be possible to add a simple "Apply Filters" button to the Search and Filtering pane?  Some of the other filters (for example the Timestamp Seek one) has a nice button labeled "Seek" that applies the configured filter, it seems that the Record Filters section should have a similar button to just re-query kafka, but with the configured Record Filters in place

**Comment by manzan46** [comment]
:+1: spend a fair bit of time on that too

**Comment by ebcFlagman** [comment]
Any work on that issue? I'm really confused about that behaviour

**Comment by Crim** [comment]
Thanks for your input.  To get a better understanding, how would you expect the filter to apply when you click the "apply filter" button?  From the head of the topic? Moving forward from the current position?

Thanks!

**Comment by Crim** [comment]
The above PR should be included in the next release.

**Comment by Crim** [comment]
released [v2.5.1](https://github.com/SourceLabOrg/kafka-webview/releases/tag/v2.5.1) which includes this.
