### ISSUE TITLE
API Usage

### ISSUE THREAD

**Issue by xstephen95x** [SourceLabOrg/kafka-webview#163]
I have over 1000 different message formats (which can constantly change) that I would like to use with this application. It would be nice if i could script the creation/updates of these message formats. 

I use the application with authentication disabled (no users) 

Is it possible to use the service as an API? 
I try to reconstruct the POST request sent by the browser with cURL, but I always get a `403:Forbidden` or  `500     <h4 class="pt-3">Houston, we have a problem!</h4>`.

**Comment by xstephen95x** [comment]
Actually, I have found a work-around.
I wrote a node js script using zombie.js to emulate doing it in-browser. This seems to be working. Feel free to close.

**Comment by Crim** [comment]
#162 and #173 maybe relevant to you, tho the work has been completed/merged yet.
