### ISSUE TITLE
How to configure Broker connection

### ISSUE THREAD

**Issue by castfe** [SourceLabOrg/kafka-webview#182]
I'm pretty new to Kafka and I decided to give this tool a try.

I was able to start up the web server, but when creating a new Cluster, I see an "admin" Broker but I don't see any config file or any way to configure that Broker.

The message I get is: "Error connecting to cluster: Invalid url in bootstrap.servers: admin"

I need to point it to the URL and Port of our Kafka broker.
Sorry if this might be obvious to somebody... Thank you in advance 👍

**Comment by Crim** [comment]
After starting the kafka-webview web service and logging in, you should be able to navigate to setup/configuration then to clusters and add a new cluster.  Are you not seeing that section?

**Comment by castfe** [comment]
Yes, I'm able to add a new cluster, but I don't see anywhere where I can add my cluster IP and Port. Here is what I see:
<img width="556" alt="Screen Shot 2019-08-05 at 7 48 14 AM" src="https://user-images.githubusercontent.com/53628114/62462434-6b313180-b755-11e9-85a2-266ae11498e7.png">

When I try to Test, I get this message (because of course, I haven't setup the IP and port hehe, but just don't know where):
<img width="1200" alt="Screen Shot 2019-08-05 at 7 51 13 AM" src="https://user-images.githubusercontent.com/53628114/62462640-e397f280-b755-11e9-9904-8abb7742e23c.png">

**Comment by Crim** [comment]
Ah the brokers input box you should enter the bootstrap url(s) for your cluster.

Example: host1:9092, host2:9092

**Comment by castfe** [comment]
That's the thing, I cannot type anything in the Brokers textbox for input :(

**Comment by Crim** [comment]
What entered the input of "admin@admin.com" into that box?  Do you have some browser plugin that is taking control of the input box?

Running the latest version from Docker I am able to enter values into that box without issue.

Let me know,
Stephen

**Comment by castfe** [comment]
Wow, I feel horrible... Yes, there was some type of plugin that was prepopulating it, and it wasn't even allowing me to edit it! Weird.
I went into Incognito mode and was able to do it.

Thank you for the help sir!

**Comment by Crim** [comment]
haha no worries, glad we got it sorted out :)
