### ISSUE TITLE
Cluster Kafka Consumer View for multiple topics

### ISSUE THREAD

**Issue by tomas12** [SourceLabOrg/kafka-webview#184]
When using Cluster Kafka Consumer view for a specific consumer that is connected to multiple topics the WebView shows diagram and information of only of one topic. I don't know if it chooses a random topic or which one. It would be great if I could see information and diagram of every topic.

**Comment by Crim** [comment]
Ah interesting.  Let me put together a test case for this and see what exactly happens.

**Comment by Crim** [comment]
I'm planning on picking this up, but likely won't get to it until ~mid-October.  

In the chance that someone is interested in picking this up before then, I say go for it! :)

**Comment by Crim** [comment]
Released 2.5.0 with this fix.
