### ISSUE TITLE
Kafka-Webview should provide option to "Stringify" ByteArray messages

### ISSUE THREAD

**Issue by mmanna-sapfgl** [SourceLabOrg/kafka-webview#190]
Currently, we don't see an option to view "Human Friendly" strings from byte[]. This would be extremely helpful to have.

**Comment by Crim** [comment]
How would you expect byte arrays to be displayed in a "human friendly" way?  Base64 encoded?  Hex? Something else?

Thanks!

**Comment by Crim** [comment]
Added a new deserializer that encodes byte[] into HEX string.  To be included in the next released version
