### ISSUE TITLE
Custom protobuf deserializer failed because of pb version conflict

### ISSUE THREAD

**Issue by kevinprotoss** [SourceLabOrg/kafka-webview#196]
Hi,

I use the kafaka-webview v2.5.0. After I upload a general protobuf deserilizer, I got the following error:

```
Error java.lang.NoSuchMethodError: com.nodeunify.jupiter.datastream.v1.FutureData.emptyLongList()Lcom/google/protobuf/Internal$LongList; (show more)
java.util.concurrent.CompletionException thrown at java.util.concurrent.CompletableFuture::encodeThrowable -> java.lang.NoSuchMethodError: com.nodeunify.jupiter.datastream.v1.FutureData.emptyLongList()Lcom/google/protobuf/Internal$LongList;
java.lang.NoSuchMethodError thrown at com.nodeunify.jupiter.datastream.v1.FutureData:: -> com.nodeunify.jupiter.datastream.v1.FutureData.emptyLongList()Lcom/google/protobuf/Internal$LongList;
```
I checked the kafka-webview uses pb `v3.6.1` while I personally use `v3.9.1`. As I know, The empty[X]List is part of GeneratedMessageV3 since 3.7.x. That means, I have currently a protobuf version conflict. How can I avoid this?

I have also seen this merge:

[ISSUE-111 - More gracefully handle protobuf serialization](https://github.com/SourceLabOrg/kafka-webview/pull/113)

Is that really required to add the pb version explicitly in the pom? I do not use the jackson deserializer which helps too less for pb deserialization. I prefer to bring my own toString function in the deserializer.

Or maybe another simple solution is just upgrade the pb dependency of kafka-webview. 

Sincerely wait for your help and response

Best regards
kevinprotoss

**Comment by kevinprotoss** [comment]
Update:

I have a temporary workaround for this issue. It works for me right now.
Just use maven shaden plugin to relocate the protobuf dependency.

Maybe you could provide this as a hint in the doc of custom deserializer in the future.

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-shade-plugin</artifactId>
    <version>3.2.1</version>
    <executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>shade</goal>
            </goals>
            <configuration>
                <relocations>
                    <relocation>
                        <pattern>com.google.protobuf</pattern>
                        <shadedPattern>shaded.com.google.protobuf</shadedPattern>
                    </relocation>
                </relocations>
            </configuration>
        </execution>
    </executions>
</plugin>
```

Bg
kevinprotoss

**Comment by Crim** [comment]
Ah, interesting problem, glad you were able to work around it.  I wonder if I should have kafka-webview shade its dependency....
