### ISSUE TITLE
Repository with ID="orgsourcelab-1031" not found

### ISSUE THREAD

**Issue by redstorm1** [SourceLabOrg/kafka-webview#204]
Step 6/16 : RUN curl -fSL -o /tmp/kafka-webview-ui-bin.zip https://oss.sonatype.org/service/local/repositories/orgsourcelab-1031/content/org/sourcelab/kafka-webview-ui/${WEBVIEW_VER}/kafka-webview-ui-${WEBVIEW_VER}-bin.zip

curl: (22) The requested URL returned error: 404

The repository for the kafka-webview-ui binary is not found.
using a browser to retrieve also failes with
Repository with ID="orgsourcelab-1031" not found

**Comment by Crim** [comment]
Updated master with a fix in this [commit](https://github.com/SourceLabOrg/kafka-webview/commit/91149f1b42927f9921c78a38b079b46c26ca4bbf)  to pull the release from github instead of maven central.

Hopefully that should resolve it for you.

Thanks!
