### ISSUE TITLE
Allow Filtering on Views Page

### ISSUE THREAD

**Issue by avina-z** [SourceLabOrg/kafka-webview#214]
On the Views Page, add an option to filter Views by Cluster. These would be very useful on configurations that have many clusters registered, each with many views defined, where normally we have to scroll in "All Views" listed to find out the one we want to browse.

**Comment by Crim** [comment]
Seems like a good idea.  

Not a real solution, but a potential short term work around is that you pass a `clusterId` parameter in the URL like `/view?clusterId=N` to filter by cluster.  

Obviously not a great solution, but the functionality already exists,  so it should be relatively simple to add a proper filter to the UI to support this.

**Comment by Crim** [comment]
How does something like this look?

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/571653/84753728-53c00780-affa-11ea-91b6-afa625364952.png">

**Comment by Crim** [comment]
Updated in release 2.6.0
