### ISSUE TITLE
How to Build this as a Single Jar/War file to deploy in server which doesn't have MVN/JDK  

### ISSUE THREAD

**Issue by ASurendar** [SourceLabOrg/kafka-webview#218]
I need to build this as a executable jar or war file to deploy it in a server. The server doesn't contain Maven or JDK. I try to build as a single jar file but i couldn't deploy it. Can you kindly Help me. Thanks

**Comment by Crim** [comment]
Hi!

So the easiest way would be to download the ZIP file from the [releases page](https://github.com/SourceLabOrg/kafka-webview/releases).  You can follow the [instructions](https://github.com/SourceLabOrg/kafka-webview#installation-from-release-distribution) on initial configuration and startup.

Or if you want to build the JAR from source, if you have JDK 1.8+ and maven installed, you can run `mvn clean package -DskipTests=true` and it will compile the jar file into your `target/` directory, as well as build a zip file with just like you can grab from the releases page.

Let me know if this helps?

**Comment by ASurendar** [comment]
Thanks for the information @Crim. It works.
