### ISSUE TITLE
Mistake in environment variable name

### ISSUE THREAD

**Issue by viastakhov** [SourceLabOrg/kafka-webview#235]
https://github.com/SourceLabOrg/kafka-webview/blob/0b5a5dcfea365269c15c4171c27a911aa348edbb/kafka-webview-ui/src/main/resources/config/base.yml#L51

Expected: ACTUATOR_PORT

**Comment by renjanmenon** [comment]
Raised PR# https://github.com/SourceLabOrg/kafka-webview/pull/270
Please approve

**Comment by Crim** [comment]
Included in 2.9.1 release, please let me know if you have any issues.

Thanks!
