### ISSUE TITLE
Feature Request: Make `requestTimeoutMs` configurable per cluster

### ISSUE THREAD

**Issue by pmeisen** [SourceLabOrg/kafka-webview#237]
When querying for the positions of larger we observe the error:
```Error Failed to get offsets by times in 15000ms```

In `KafkaClientConfigUtil.java` it looks like the timeout (15s) is hard coded:
```private final int requestTimeoutMs = 15000;```

Would it be possible to make it configurable via the UI for specific cluster?

**Comment by Crim** [comment]
So I believe it should already be configurable via the cluster config under `Custom Client Properties`

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/571653/125180595-b05e1800-e236-11eb-89db-f077f5c8f60f.png">

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/571653/125180598-bce27080-e236-11eb-94a8-8eb6174f7823.png">


Setting that property should override the default of 15 seconds.  Give it a go and let me know if that solves it for you?

**Comment by pmeisen** [comment]
You are right, it is already available. Thank you so much, it works like a charm.

**Comment by Crim** [comment]
awesome, glad to hear it!
