### ISSUE TITLE
Security Update

### ISSUE THREAD

**Issue by kobayashilin** [SourceLabOrg/kafka-webview#244]
Hi, 

It seems that there a lot of security pull requests are waiting for merged.

Do we have any new release milestone for these security patches?

Thanks!

![image](https://user-images.githubusercontent.com/4756036/146287275-45ded42d-ebab-47dc-8745-b8dc8570a563.png)

Yan-Ting

**Comment by Crim** [comment]
Hey! 

I'll try to take a look today and see which dependencies I can get updated.

Thanks!
Stephen

**Comment by Crim** [comment]
I've reviewed and updated dependencies with outstanding security issues, short of upgrading to a newer springboot release, which would require more effort (both in my own time to validate, and for end users upgrading) so I'm going to push that off for the time being.

The biggest remaining security issue that I am aware of is with the outdated version of `gulp`, but that is a build/developer dependency and not packaged w/ the resulting binary/application that end users would consume.

I'll give this one more pass validating and cut a release in a day or so.
Thanks

**Comment by Crim** [comment]
Published release v2.8.1 with the updated dependencies.
