### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by simplesteph** [SourceLabOrg/kafka-webview#47]
I would love to give this a spin, but it'd be amazing if it had a Docker image to quickly just get it up and running against existing setups

**Comment by Crim** [comment]
That sounds like a great idea.  I'll try to put something together here shortly.

**Comment by Crim** [comment]
@simplesteph Is this what you had in mind: #48 

Still a work in progress but:
https://hub.docker.com/r/sourcelaborg/kafka-webview/tags/

```bash
docker run -p 8080:8080 sourcelaborg/kafka-webview:latest
```

**Comment by simplesteph** [comment]
something along those lines yes. I've commented on the PR

**Comment by Crim** [comment]
Thanks!  Docker is definitely not a strong point for me, so I appreciate the feed back :)

**Comment by Crim** [comment]
Merged in the above PR.  If you have any other suggestions let me know!  

Thanks!
