### ISSUE TITLE
Crash listing topics when filter available

### ISSUE THREAD

**Issue by s0rbus** [SourceLabOrg/kafka-webview#49]
If I add a filter (I was using the example ones unmodified), then go to create a view, after I have selected my cluster the application crashes and no topics are available in the list. If I do not have any filters, then it all works fine.

The stack trace is very long, but I did spot this, don't know if it is relevant

ERROR 23754 --- [nio-7070-exec-1] org.thymeleaf.TemplateEngine             : [THYMELEAF][http-nio-7070-exec-1] Exception processing template "configuration/view/create": An error happened during template parsing (template: "class path resource [templates/configuration/view/create.html]")

org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "class path resource [templates/configuration/view/create.html]")

and later....

Caused by: org.attoparser.ParseException: Exception evaluating SpringEL expression: "filterParameters.containsKey(filter.id)" (template: "configuration/view/create" - line 352, col 45)

and later....

ERROR 23754 --- [nio-7070-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "class path resource [templates/configuration/view/create.html]")] with root cause

I got the success message when setting up the filter. I used the StringSearchFilter, specified where to find the jar file (I used the 'with-dependencies' one), and set Classpath to examples.filter.StringSearchFilter

**Comment by Crim** [comment]
I was able to replicate this.  Let me play around with it a bit and figure out whats going on.  Thanks!

**Comment by Crim** [comment]
Thanks for the bug report.  I've published a fix for it and will work on getting a new version release packaged up and published as well. 👍

**Comment by s0rbus** [comment]
I've pulled the update, built and run it. Working fine now. Thanks for the quick response. If I may make one other minor comment.... personally I wouldn't call the config value in the filter Classpath. I would call it 'Fully qualified class name'. It confused me for a while what exactly it was requiring but the full class name was the only thing that made sense. A Classpath is quite different.

**Comment by Crim** [comment]
You're right!  Good suggestion!

**Comment by Crim** [comment]
I still need to publish an updated artifact to maven, but I cut a release and uploaded an updated docker image.

Thanks for the feedback!
