### ISSUE TITLE
Error "No serializer found for class..."

### ISSUE THREAD

**Issue by Crim** [SourceLabOrg/kafka-webview#75]
When deserializing from Kafka into objects that have no registered jackson serializer you get the error below.

We should handle this situation better by telling jackson to fall back to using that objects toString() method.

` Error Could not write JSON: No serializer found for class com.google.protobuf.UnknownFieldSet$Parser and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS); nested exception is com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class com.google.protobuf.UnknownFieldSet$Parser and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: org.sourcelab.kafka.webview.ui.manager.kafka.dto.KafkaResults["results"]->java.util.Collections$UnmodifiableRandomAccessList[0]->org.sourcelab.kafka.webview.ui.manager.kafka.dto.KafkaResult["value"]

**Comment by Ordain3523** [comment]
have you found the answer?
