### ISSUE TITLE
Cluster and SSL config via file

### ISSUE THREAD

**Issue by nucknorris** [SourceLabOrg/kafka-webview#77]
Hi, 

I'm using kafka-webview and I really like it so far. One big problem is, that most of the config has to be done via the UI. Is there any way to pre-configure clusters and the SSL config in the `config.yml`?

**Comment by Crim** [comment]
As of today there exists no way to define clusters via the config.yml file.  I'm trying to make sure I understand the use case for defining them there, do you have a large number of clusters?

**Comment by nucknorris** [comment]
We have a development environment for multiple developers that is based on docker-compose. It would be nice to have a way to check in the config for the setup, so that not every dev has to do it over and over again. 

Especially since the SSL config is pretty extensive.

**Comment by nucknorris** [comment]
To clarify our use case a bit more:

Goal would be to start kafka-webview with the pre-configured local docker-compose based Kafka cluster. This would also include SSL since our DevEnv setup already uses that between the Kafka cluster and the producer/consumers.

**Comment by Crim** [comment]
Is it possible for you to build a base image with the database already configured with your setup?

**Comment by nucknorris** [comment]
Yes this would also be an option. It's not ideal, but since the images are "baked in" the DevEnv anyway, it would be ok.

**Comment by Crim** [comment]
So all of the 'configuration' for kafka-webview is maintained within an internal sql-lite database, not flat configuration files. Because of this I think it'd be difficult to get kafka-webview to load a set of configs from a file on startup along with figuring out how to load the SSL keystores, encrypt passwords, etc..
