### ISSUE TITLE
can't log in! what is the default username and password

### ISSUE THREAD

**Issue by dawsongzhao** [SourceLabOrg/kafka-webview#88]
what is the default username and password

**Comment by Crim** [comment]
The default credentials are listed in the README until the section [Logging in for the first time](https://github.com/sourcelaborg/kafka-webview#logging-in-for-the-first-time).  Do those credentials not work?

**Comment by dawsongzhao** [comment]
> The default credentials are listed in the README until the section [Logging in for the first time](https://github.com/sourcelaborg/kafka-webview#logging-in-for-the-first-time). Do those credentials not work?

it's ok now. thank you.

**Comment by surakula** [comment]
unable to login with admin@example.com and admin

**Comment by Crim** [comment]
Which release are you using?  How are you running it? Docker? or from the release package?

**Comment by surakula** [comment]
Hi There,

I used docker image and manually download the source code ran buildandrun script I see the same issue unable to login with default user name and password.

Than I change the config.yml —> authenticate to false... I able to go to home page. But I when I try to add Kafka config cluster details it’s throws 500... Houston error.

I suspect some issue with DB persistence issue.

Thanks,
Suresh Akula.

On Oct 9, 2018, at 1:37 AM, Steviep <notifications@github.com<mailto:notifications@github.com>> wrote:


Which release are you using? How are you running it? Docker? or from the release package?

**Comment by Crim** [comment]
Are you able to provide any stack traces or errors from the logs?  Which OS are you running on?

**Comment by surakula** [comment]
Mac, I don’t see any errors in docker logs.



On Oct 9, 2018, at 3:56 PM, Steviep <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you able to provide any stack traces or errors from the logs? Which OS are you running on?

**Comment by Crim** [comment]
and you're using the following command to run the docker image: 

`docker run -it -p 8080:8080 -v kafkawebview_data:/app/data sourcelaborg/kafka-webview:latest` ?

I've pruned/removed all of my images locally and ran the above command on OSX using Docker Version 18.03.1-ce-mac65 (24312) and it downloads and starts up without any errors and I can login OK.

Without any errors from the logs, it's difficult to determine whats going wrong
